services:
  - type: web
    name: hotel-booking-backend
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
